version: "3.8"
services:
  mysql:
    image: mysql:latest
    container_name: piggy-db
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=piggy
      - MYSQL_DATABASE=piggy
      - MYSQL_USER=piggy
      - MYSQL_PASSWORD=piggy
  php:
    image: ambientum/php:latest-nginx
    container_name: piggy-api
    volumes:
      - .:/var/www/app
    ports:
      - 8000:8080
    links:
      - mysql
    environment:
      - XDEBUG_ENABLED=true